/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormBuilderRouteImport } from './routes/form-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormBuilderIndexRouteImport } from './routes/form-builder/index'
import { Route as FormBuilderDemosGeneReusabilityRouteImport } from './routes/form-builder/demos/gene-reusability'

const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderIndexRoute = FormBuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormBuilderRoute,
} as any)
const FormBuilderDemosGeneReusabilityRoute =
  FormBuilderDemosGeneReusabilityRouteImport.update({
    id: '/demos/gene-reusability',
    path: '/demos/gene-reusability',
    getParentRoute: () => FormBuilderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRouteWithChildren
  '/form-builder/': typeof FormBuilderIndexRoute
  '/form-builder/demos/gene-reusability': typeof FormBuilderDemosGeneReusabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderIndexRoute
  '/form-builder/demos/gene-reusability': typeof FormBuilderDemosGeneReusabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRouteWithChildren
  '/form-builder/': typeof FormBuilderIndexRoute
  '/form-builder/demos/gene-reusability': typeof FormBuilderDemosGeneReusabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/form-builder'
    | '/form-builder/'
    | '/form-builder/demos/gene-reusability'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form-builder' | '/form-builder/demos/gene-reusability'
  id:
    | '__root__'
    | '/'
    | '/form-builder'
    | '/form-builder/'
    | '/form-builder/demos/gene-reusability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormBuilderRoute: typeof FormBuilderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/form-builder': {
      id: '/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder/': {
      id: '/form-builder/'
      path: '/'
      fullPath: '/form-builder/'
      preLoaderRoute: typeof FormBuilderIndexRouteImport
      parentRoute: typeof FormBuilderRoute
    }
    '/form-builder/demos/gene-reusability': {
      id: '/form-builder/demos/gene-reusability'
      path: '/demos/gene-reusability'
      fullPath: '/form-builder/demos/gene-reusability'
      preLoaderRoute: typeof FormBuilderDemosGeneReusabilityRouteImport
      parentRoute: typeof FormBuilderRoute
    }
  }
}

interface FormBuilderRouteChildren {
  FormBuilderIndexRoute: typeof FormBuilderIndexRoute
  FormBuilderDemosGeneReusabilityRoute: typeof FormBuilderDemosGeneReusabilityRoute
}

const FormBuilderRouteChildren: FormBuilderRouteChildren = {
  FormBuilderIndexRoute: FormBuilderIndexRoute,
  FormBuilderDemosGeneReusabilityRoute: FormBuilderDemosGeneReusabilityRoute,
}

const FormBuilderRouteWithChildren = FormBuilderRoute._addFileChildren(
  FormBuilderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormBuilderRoute: FormBuilderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
