name: Build and Push to ECR

on:
  push:
    branches: [main, master, feature/*]
    paths:
      - "Dockerfile*"
      - "docker-compose.yml"
      - "nginx.conf"
      - ".dockerignore"
      - "helixium-web/**"
      - ".github/workflows/**"
      - "terraform/**"
  pull_request:
    branches: [main, master, feature/*]
    paths:
      - "Dockerfile*"
      - "docker-compose.yml"
      - "nginx.conf"
      - ".dockerignore"
      - "helixium-web/**"
      - ".github/workflows/**"
      - "terraform/**"
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Images to ECR
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug environment
        run: |
          echo "GitHub event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "AWS Region configured: ${{ vars.AWS_REGION != '' }}"
          echo "ECR Repository URL configured: ${{ secrets.ECR_REPOSITORY_URL != '' }}"
          echo "AWS Access Key configured: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS Secret Key configured: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Verify AWS configuration
        run: |
          echo "Testing AWS configuration..."
          aws sts get-caller-identity
          echo "AWS configuration verified successfully"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/helixium-web
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push production Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push development Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/helixium-web-dev:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image URIs
        run: |
          echo "Production image: ${{ steps.login-ecr.outputs.registry }}/helixium-web:${{ github.sha }}"
          echo "Development image: ${{ steps.login-ecr.outputs.registry }}/helixium-web-dev:${{ github.sha }}"
          echo "Latest production image: ${{ steps.login-ecr.outputs.registry }}/helixium-web:latest"
